In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [3]:
print(arr[0,1])
print(arr[2,2])

2
9


In [4]:
print(arr[-1,-2])
print(arr[-3,-3])

8
1


In [7]:
#General form: arr[start:stop:step]
print(arr[0:2, 1:3])  # row0-1, cols 1-2

[[2 3]
 [5 6]]


In [10]:
print(arr[::2, ::2])

[[999   3]
 [  7   9]]


In [ ]:
slice_arr = arr[0, :2]
slice_arr[0] = 999

In [11]:
print(arr[0])

[999   2   3]


In [12]:
copy_arr = arr[1].copy() #independent copy
copy_arr[0] = 555

In [13]:
print(arr[1])

[4 5 6]
